test:
  layout: layout
  site_url: barcelonaonrails.local
  site_email: admin@barcelonaonrails.com
  
development:
  layout: layout
  site_url: barcelonaonrails.local
  site_email: admin@barcelonaonrails.com
  
production:
  layout: coming
  site_url: barcelonaonrails.com
  site_email: admin@barcelonaonrails.com